/** Actions recorded on auditLogs/{auditLogId}. */
export const AUDIT_ACTIONS = {
  SALON_OWNER_REGISTERED: "SALON_OWNER_REGISTERED",
  APPLICATION_APPROVED: "APPLICATION_APPROVED",
  APPLICATION_REJECTED: "APPLICATION_REJECTED",
  APPLICATION_RESUBMITTED: "APPLICATION_RESUBMITTED",
  SALON_SUSPENDED: "SALON_SUSPENDED",
  SALON_REACTIVATED: "SALON_REACTIVATED",
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];

/** Actions recorded on salonVerificationHistory/{historyId}. */
export const VERIFICATION_HISTORY_ACTIONS = {
  SUBMITTED: "SUBMITTED",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  RESUBMITTED: "RESUBMITTED",
  SUSPENDED: "SUSPENDED",
  REACTIVATED: "REACTIVATED",
} as const;

export type VerificationHistoryAction =
  (typeof VERIFICATION_HISTORY_ACTIONS)[keyof typeof VERIFICATION_HISTORY_ACTIONS];
