/** Actions recorded on auditLogs/{auditLogId}. */
export const AUDIT_ACTIONS = {
  SALON_OWNER_REGISTERED: "SALON_OWNER_REGISTERED",
  APPLICATION_APPROVED: "APPLICATION_APPROVED",
  APPLICATION_REJECTED: "APPLICATION_REJECTED",
  APPLICATION_RESUBMITTED: "APPLICATION_RESUBMITTED",
  SALON_SUSPENDED: "SALON_SUSPENDED",
  SALON_REACTIVATED: "SALON_REACTIVATED",
  CATEGORY_CREATED: "CATEGORY_CREATED",
  CATEGORY_UPDATED: "CATEGORY_UPDATED",
  CATEGORY_DELETED: "CATEGORY_DELETED",
  SALON_PROFILE_UPDATED: "SALON_PROFILE_UPDATED",
  SERVICE_CREATED: "SERVICE_CREATED",
  SERVICE_UPDATED: "SERVICE_UPDATED",
  SERVICE_STATUS_CHANGED: "SERVICE_STATUS_CHANGED",
  STAFF_CREATED: "STAFF_CREATED",
  STAFF_UPDATED: "STAFF_UPDATED",
  STAFF_STATUS_CHANGED: "STAFF_STATUS_CHANGED",
  STAFF_LEAVE_ADDED: "STAFF_LEAVE_ADDED",
  STAFF_LEAVE_REMOVED: "STAFF_LEAVE_REMOVED",
  BOOKING_CREATED: "BOOKING_CREATED",
  BOOKING_STAFF_ASSIGNED: "BOOKING_STAFF_ASSIGNED",
  BOOKING_STAFF_DECISION: "BOOKING_STAFF_DECISION",
  BOOKING_DECLINED: "BOOKING_DECLINED",
  BOOKING_CANCELLED: "BOOKING_CANCELLED",
  BOOKING_RESCHEDULED: "BOOKING_RESCHEDULED",
  BOOKING_COMPLETED: "BOOKING_COMPLETED",
  BOOKING_NO_SHOW: "BOOKING_NO_SHOW",
  BOOKING_NOTES_UPDATED: "BOOKING_NOTES_UPDATED",
  CUSTOMER_NOTES_UPDATED: "CUSTOMER_NOTES_UPDATED",
  WORKING_HOURS_UPDATED: "WORKING_HOURS_UPDATED",
  TIME_OFF_ADDED: "TIME_OFF_ADDED",
  TIME_OFF_REMOVED: "TIME_OFF_REMOVED",
  SALON_SETTINGS_UPDATED: "SALON_SETTINGS_UPDATED",
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];

/** Actions recorded on salonVerificationHistory/{historyId}. */
export const VERIFICATION_HISTORY_ACTIONS = {
  SUBMITTED: "SUBMITTED",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  RESUBMITTED: "RESUBMITTED",
  SUSPENDED: "SUSPENDED",
  REACTIVATED: "REACTIVATED",
} as const;

export type VerificationHistoryAction =
  (typeof VERIFICATION_HISTORY_ACTIONS)[keyof typeof VERIFICATION_HISTORY_ACTIONS];
