export const NOTIFICATION_TYPES = {
  SALON_APPLICATION_SUBMITTED: "SALON_APPLICATION_SUBMITTED",
  APPLICATION_APPROVED: "APPLICATION_APPROVED",
  APPLICATION_REJECTED: "APPLICATION_REJECTED",
  APPLICATION_RESUBMITTED: "APPLICATION_RESUBMITTED",
  SALON_SUSPENDED: "SALON_SUSPENDED",
  SALON_REACTIVATED: "SALON_REACTIVATED",
  NEW_BOOKING_REQUEST: "NEW_BOOKING_REQUEST",
  STAFF_ACCEPTED_BOOKING: "STAFF_ACCEPTED_BOOKING",
  STAFF_REJECTED_BOOKING: "STAFF_REJECTED_BOOKING",
  BOOKING_CANCELLED_BY_CUSTOMER: "BOOKING_CANCELLED_BY_CUSTOMER",
  UPCOMING_APPOINTMENT: "UPCOMING_APPOINTMENT",
} as const;

export type NotificationType = (typeof NOTIFICATION_TYPES)[keyof typeof NOTIFICATION_TYPES];

export const ALL_NOTIFICATION_TYPES: NotificationType[] = Object.values(NOTIFICATION_TYPES);
