export const NOTIFICATION_TYPES = {
  SALON_APPLICATION_SUBMITTED: "SALON_APPLICATION_SUBMITTED",
  APPLICATION_APPROVED: "APPLICATION_APPROVED",
  APPLICATION_REJECTED: "APPLICATION_REJECTED",
  APPLICATION_RESUBMITTED: "APPLICATION_RESUBMITTED",
  SALON_SUSPENDED: "SALON_SUSPENDED",
  SALON_REACTIVATED: "SALON_REACTIVATED",
} as const;

export type NotificationType = (typeof NOTIFICATION_TYPES)[keyof typeof NOTIFICATION_TYPES];

export const ALL_NOTIFICATION_TYPES: NotificationType[] = Object.values(NOTIFICATION_TYPES);
